visited_places/models.py
from datetime import datetime
from sqlalchemy import desc
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from visited_places import db


class Bookmark(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.Text, nullable=False)
    date = db.Column(db.DateTime, default=datetime.utcnow)
    continent = db.Column(db.String(100))
    country = db.Column(db.String(100))
    city = db.Column(db.String(100))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    @staticmethod
    def latest(num):
        return Bookmark.query.order_by(desc(Bookmark.date)).limit(num)


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    password_hash = db.Column(db.String)
    bookmarks = db.relationship('Bookmark', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError('password: write-only field')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def get_by_username(username):
        return User.query.filter_by(username=username).first()

visited_places/forms.py
from flask_wtf import Form
from wtforms.fields.html5 import URLField
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, url, Length, Regexp, EqualTo, Email, ValidationError

from visited_places.models import User


class BookmarkForm(Form):
    url = URLField('The URL with information about the place:', validators=[DataRequired(), url()])
    continent = StringField('Add continent where the place is located: ')
    country = StringField('Add country of place: ')
    city = StringField('Add name of place: ')
    submit = SubmitField('Submit')


class LoginForm(Form):
    username = StringField('Your username:', validators=[DataRequired()])
    password = PasswordField('Password:', validators=[DataRequired()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField('Log in')


class SignUpForm(Form):
    username = StringField('Username:',
                           validators=[
                               DataRequired(),
                               Length(3, 80),
                               Regexp('^[A-Za-z0-9_]{3,}$',
                                      message='Username consist of number, letters and underscores.')
                           ])
    password = PasswordField('Password:',
                             validators=[
                                 DataRequired(),
                                 EqualTo('password2', message="Password must match")
                             ])
    password2 = PasswordField('Confirm password',
                              validators=[DataRequired()])
    email = StringField('Email:',
                        validators=[
                            DataRequired(),
                            Length(5, 120),
                            Email()
                        ])
    submit = SubmitField('Sign up')

    def validate_email(self, email_field):
        if User.query.filter_by(email=email_field.data).first():
            raise ValidationError('There is already user with this e-mail.')

    def validate_username(self, username_field):
        if User.query.filter_by(username=username_field.data).first():
            raise ValidationError('There username is already taken. Please choose something else.')

visited_places/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

basedir = os.path.abspath(os.path.dirname(__file__))
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'user.login'


def create_app():
    visited_places_app = Flask(__name__)
    visited_places_app.config["SECRET_KEY"] = b'\x82\x8a\\\xb5\xbcd\x96\xb1\xb7das\x10e\x1b\x03'
    visited_places_app.config['DEBUG'] = True
    visited_places_app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{os.path.join(basedir, 'visited_places.db')}"

    from visited_places.views.default_views import main_bp
    from visited_places.views.user_views import user_bp
    from visited_places.views.bm_views import bm_bp

    visited_places_app.register_blueprint(main_bp)
    visited_places_app.register_blueprint(user_bp)
    visited_places_app.register_blueprint(bm_bp)

    db.init_app(visited_places_app)
    login_manager.init_app(visited_places_app)

    return visited_places_app


app = create_app()

visited_places/views/bm_views.py
from flask import Blueprint, flash, url_for, render_template, redirect, abort, request
from flask_login import login_required, current_user

from visited_places import db
from visited_places.forms import BookmarkForm
from visited_places.models import Bookmark

bm_bp = Blueprint('bm', __name__, url_prefix="/bookmarks")


@bm_bp.route("/add_bookmark", methods=['GET', 'POST'])
@login_required
def add_bookmark():
    form = BookmarkForm()

    if form.validate_on_submit():
        url = form.url.data
        continent = form.continent.data
        country = form.country.data
        city = form.city.data

        bm = Bookmark(user=current_user, url=url, continent=continent, country=country, city=city)
        db.session.add(bm)
        db.session.commit()

        flash(f"Stored {city}")
        return redirect(url_for('user.user', username=current_user.username))
    return render_template('add.html', form=form)


@bm_bp.route("/edit/<int:bookmark_id>", methods=['GET', 'POST'])
@login_required
def edit_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)

    if current_user != bookmark.user:
        abort(403)

    form = BookmarkForm(obj=bookmark)
    if form.validate_on_submit():
        form.populate_obj(bookmark)
        db.session.commit()
        flash(f"It works")
        return redirect(url_for('user.user', username=current_user.username))
    return render_template('bookmark_form.html', form=form, title="Edit bookmark")


@bm_bp.route('/delete/<int:bookmark_id>', methods=['GET', 'POST'])
@login_required
def delete_bookmark(bookmark_id):
    bookmark = Bookmark.query.get_or_404(bookmark_id)

    if current_user != bookmark.user:
        abort(403)

    if request.method == 'POST':
        db.session.delete(bookmark)
        db.session.commit()

        flash(f"Deleted {bookmark.city}")
        return redirect(url_for('user.user', username=current_user.username))
    else:
        flash("Please confirm deleting the bookmark.")
    return render_template('confirm_delete.html', bookmark=bookmark, nolinks=True)

visited_places/views/default_views.py
from flask import render_template, Blueprint

from visited_places import login_manager
from visited_places.models import Bookmark, User

main_bp = Blueprint("main", __name__, url_prefix="/")


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main_bp.route("/")
@main_bp.route("/index")
def index():
    return render_template("index.html", bookmarks=Bookmark.latest(5))


@main_bp.errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@main_bp.errorhandler(500)
def server_error(e):
    return render_template("500.html"), 500


@main_bp.errorhandler(403)
def forbidden(e):
    return "strona nie działa"

visited_places/views/user_views.py
from flask import flash, request, url_for, render_template, redirect, Blueprint
from flask_login import login_user, logout_user

from visited_places import db
from visited_places.forms import LoginForm, SignUpForm
from visited_places.models import User

user_bp = Blueprint("user", __name__, url_prefix="/users")


@user_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.get_by_username(form.username.data)
        if user is not None and user.check_password(form.password.data):
            login_user(user, form.remember_me.data)
            flash(f"Logged in successfully as {user.username}")
            return redirect(request.args.get('next') or url_for('main.index'))
        flash(f"Incorrect username or password")
    return render_template('login.html', form=form)


@user_bp.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@user_bp.route("/signup", methods=['GET', 'POST'])
def signup():
    form = SignUpForm()

    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data, password=form.password.data)

        db.session.add(user)
        db.session.commit()

        flash(f"Welcome {user.username}. Please login")
        return redirect(url_for('user.login'))
    return render_template('signup.html', form=form)


@user_bp.route('/user/<username>')
def user(username):
    user_db = User.query.filter_by(username=username).first_or_404()
    return render_template('user.html', user=user_db)

visited_places/templates/add.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Visited Places - Add new place
{% endblock %}

{% block content %}

<section>
    <h1>Add a New Place</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <table>
            {{ render_field(form.url, size=50) }}
            {{ render_field(form.continent, size=50) }}
            {{ render_field(form.country, size=50) }}
            {{ render_field(form.city, size=50) }}

            <tr class="submit">
                <td></td>
                <td>
                    <button type="submit">Submit</button>
                </td>
            </tr>
        </table>
    </form>
</section>

{% endblock %}

{% block sidebar %}
{% endblock %}

visited_places/templates/base.html
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

    <script src="js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>

<div class="header-container">
    <header class="wrapper clearfix">
        <a href="{{ url_for('main.index') }}">
            <h1 class="title">Visited Places</h1>
        </a>
        <nav>
            <ul>
                <li><a href="{{ url_for('bm.add_bookmark') }}">Add New Place</a></li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('user.logout') }}">Sign out</a></li>
                    <li><a href="{{ url_for('user.user', username=current_user.username) }}">Account</a></li>
                {% else %}
                    <li><a href="{{ url_for('user.signup') }}">Sign Up</a></li>
                    <li><a href="{{ url_for('user.login') }}">Login</a></li>

                {% endif %}
            </ul>
        </nav>
    </header>
</div>

<div class="main-container">
    <div class="main wrapper clearfix">

        <article class="flashes">
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}
        </article>

        {% block content %}
        {% endblock %}

        {% block sidebar %}
        <aside>
            <h3>aside</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor.
                Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper
                consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor. Etiam
                ullamcorper lorem dapibus velit suscipit ultrices.</p>
        </aside>
        {% endblock %}

    </div> <!-- #main -->
</div> <!-- #main-container -->

<div class="footer-container">
    <footer class="wrapper">
        <h3>footer</h3>
    </footer>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

<script src="js/main.js"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
<script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');





</script>
</body>
</html>

visited_places/templates/bookmark.html
<div class="bookmark">
    <a href="{{ bookmark.url }}" class="header">
        <h3 class="description">
            {{ bookmark.city|truncate(50, killwords=True) }}
        </h3>
        <span class="url">
            {{ bookmark.url|truncate(50, killwords=True) }}
        </span>
    </a>
    <div class="info">
        {% if current_user == bookmark.user and not nolinks %}
        <span class="editlinks">
            <a href="{{ url_for('bm.edit_bookmark', bookmark_id=bookmark.id) }}">Edit</a>
            <a href="{{ url_for('bm.delete_bookmark', bookmark_id=bookmark.id) }}">Delete</a>
        </span>
        {% endif %}
    </div>
</div>

visited_places/templates/bookmark_form.html
{% extends 'base.html' %}
{% from 'form_macros.html' import render_field %}

{% block content %}
<section>
    <h1>{{ title }}</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <table>
            {{ render_field(form.url, size=50) }}
            {{ render_field(form.continent, size=50) }}
            {{ render_field(form.country, size=50) }}
            {{ render_field(form.city, size=50) }}
            {{ render_field(form.submit) }}
        </table>
    </form>
</section>
{% endblock%}

visited_places/templates/bookmark_list.html
<ul class="bookmarks">
    {% for bookmark in bookmarks %}
        <li>
            {% include 'bookmark.html' %}
        </li>
    {% endfor %}
</ul>

visited_places/templates/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Visited_places - Delete bookmark
{% endblock %}

{% block content %}

<section>
    <h1>Confirm Delete</h1>
    {% include "bookmark.html" %}
    <form
            action="{{ url_for('bm.delete_bookmark', bookmark_id=bookmark.id) }}"
            method="post"
    >
    <span>Are You sure?</span><br><br>
    <a href="{{ url_for('user.user', username=current_user.username) }}">No, leave it.</a>
    <button type="submit">Yes, delete it.</button>
    </form>
</section>

{% endblock %}

visited_places/templates/form_macros.html
{% macro render_field(field) %}

    <tr {% if field.errors %} class="error" {% endif %}>
        <td>{{ field.label }}</td>
        <td>{{ field(**kwargs) }}</td>
    </tr>

    <tr class="error">
        <td></td>
        <td>
            <ul>
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>

{% endmacro %}

visited_places/templates/index.html
{% extends "base.html" %}

{% block title %}
Visited Places - Welcome.
{% endblock %}

{% block content %}

<article>
    <header>
        <h1>Welcome</h1>
        <p>Visited Places is a page where you can add_bookmark a recommendation of places worth visiting.</p>
    </header>
    <section>
        <h2>Recently added</h2>
        {% if bookmarks %}
        <ul>
            {% for bm in bookmarks %}
            <li>{{ bm.user.username }} added
                <a href="{{ bm.url }}" target="_blank">
                    {% if bm.city %}
                    {{ bm.city }}
                    {% else %}
                    {{ bm.url }}
                    {% endif %}
                </a>
                {{ bm.continent }} {{ bm.country }}
            </li>
            {% endfor %}
        </ul>
        {% else %}
        No places added yet.
        {% endif %}
    </section>
</article>

{% endblock %}

visited_places/templates/login.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Visited_places - login
{% endblock %}

{% block content %}

<section>
    <h1>Please login</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <table>
            {{ render_field(form.username, size=50) }}
            {{ render_field(form.password, size=50) }}
            {{ render_field(form.remember_me) }}
            {{ render_field(form.submit) }}
        </table>
    </form>
</section>

{% endblock %}

visited_places/templates/signup.html
{% extends "base.html" %}
{% from "form_macros.html" import render_field %}

{% block title %}
Visited_places - signup
{% endblock %}

{% block content %}

<section>
    <h1>Create an account</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <table>
            {{ render_field(form.username, size=50) }}
            {{ render_field(form.email, size=50) }}
            {{ render_field(form.password, size=50) }}
            {{ render_field(form.password2, size=50) }}
            {{ render_field(form.submit) }}
        </table>
    </form>
</section>

{% endblock %}


{% block sidebar %}
{% endblock %}

visited_places/templates/temp.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Visited Places</title>
</head>
<body>

    <h1>Visited Places app</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad, commodi, corporis eligendi est fuga in incidunt iste, libero mollitia nisi nobis porro qui repudiandae totam.</p>

</body>
</html>

visited_places/templates/user.html
{% extends "base.html" %}

{% block title %}
Visited_places -- Bookmarks for user {{ user.username }}
{% endblock %}

{% block content %}

<article>
    <header>
        <h1>Bookmarks for {{ user.username }}</h1>
        <ul>
            {% if user.bookmarks.count() > 0 %}
                {% with bookmarks=user.bookmarks %}
                    {% include "bookmark_list.html" %}
                {% endwith %}
            {% else %}
                <li>This user has not added any bookmarks yet.</li>
            {% endif %}
        </ul>
    </header>
</article>

{% endblock %}